import SEO from "../components/SEO";
import Header from "../components/Header";
import Footer from "../components/Footer";

export default function Terms() {
  return (
    <div className="min-h-screen bg-[#0B0E14] text-[#F4F5F7]">
      <SEO title="Terms of Service — CoolBG.com" description="Terms governing use of CoolBG.com and backgrounds exported from it." path="/terms" />
      <Header variant="compact" />
      <main className="max-w-2xl mx-auto px-5 sm:px-8 py-14">
        <h1 className="font-display font-bold text-3xl mb-6">Terms of Service</h1>
        <div className="space-y-5 text-sm leading-relaxed text-white/70">
          <p className="text-white/40 font-mono text-xs">Last updated: August 2026</p>
          <p>By using CoolBG.com you agree to use the site and any exported backgrounds lawfully. Backgrounds generated by the tool are provided "as is," free for personal and commercial use, with no warranty of any kind.</p>
          <p>You may not use automated means to scrape or overload the service, attempt to interfere with its normal operation, or misrepresent the tool as your own without modification.</p>
          <p>These terms may be updated from time to time. Continued use of the site after changes constitutes acceptance of the revised terms.</p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
